export type Theme = 'light' | 'dark' | 'gray' | 'contrast';

export const themes = {
  light: {
    primary: 'bg-indigo-600 hover:bg-indigo-700',
    secondary: 'bg-purple-600 hover:bg-purple-700',
    accent: 'bg-pink-600 hover:bg-pink-700',
    background: 'bg-white',
    text: 'text-gray-900',
    textMuted: 'text-gray-500',
    border: 'border-gray-200',
    sidebar: 'bg-white',
    sidebarHover: 'hover:bg-gray-50',
    card: 'bg-white shadow-lg',
    input: 'bg-white border-gray-300',
    success: 'bg-green-600 hover:bg-green-700',
    warning: 'bg-yellow-600 hover:bg-yellow-700',
    danger: 'bg-red-600 hover:bg-red-700',
  },
  dark: {
    primary: 'bg-indigo-500 hover:bg-indigo-600',
    secondary: 'bg-purple-500 hover:bg-purple-600',
    accent: 'bg-pink-500 hover:bg-pink-600',
    background: 'bg-gray-900',
    text: 'text-white',
    textMuted: 'text-gray-300',
    border: 'border-gray-700',
    sidebar: 'bg-gray-800',
    sidebarHover: 'hover:bg-gray-700',
    card: 'bg-gray-800 shadow-xl',
    input: 'bg-gray-800 border-gray-600',
    success: 'bg-green-500 hover:bg-green-600',
    warning: 'bg-yellow-500 hover:bg-yellow-600',
    danger: 'bg-red-500 hover:bg-red-600',
  },
  gray: {
    primary: 'bg-gray-600 hover:bg-gray-700',
    secondary: 'bg-gray-500 hover:bg-gray-600',
    accent: 'bg-gray-400 hover:bg-gray-500',
    background: 'bg-gray-100',
    text: 'text-gray-900',
    textMuted: 'text-gray-600',
    border: 'border-gray-300',
    sidebar: 'bg-gray-200',
    sidebarHover: 'hover:bg-gray-300',
    card: 'bg-white shadow-md',
    input: 'bg-white border-gray-400',
    success: 'bg-gray-600 hover:bg-gray-700',
    warning: 'bg-gray-500 hover:bg-gray-600',
    danger: 'bg-gray-700 hover:bg-gray-800',
  },
  contrast: {
    primary: 'bg-black hover:bg-gray-900',
    secondary: 'bg-gray-900 hover:bg-black',
    accent: 'bg-white hover:bg-gray-100',
    background: 'bg-white',
    text: 'text-black',
    textMuted: 'text-gray-900',
    border: 'border-black',
    sidebar: 'bg-white',
    sidebarHover: 'hover:bg-gray-100',
    card: 'bg-white shadow-xl border-2 border-black',
    input: 'bg-white border-2 border-black',
    success: 'bg-green-900 hover:bg-green-800',
    warning: 'bg-yellow-900 hover:bg-yellow-800',
    danger: 'bg-red-900 hover:bg-red-800',
  },
};